# Generated by Django 5.0.4 on 2024-07-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_feedback_fitness'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=50)),
                ('pprice', models.CharField(max_length=50)),
                ('pnumber', models.CharField(max_length=50)),
                ('pimage', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
