# Generated by Django 5.0.4 on 2024-07-11 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_assets_pimage_alter_assets_pname'),
    ]

    operations = [
        migrations.CreateModel(
            name='userCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=100)),
                ('p_price', models.CharField(max_length=50)),
                ('p_image', models.CharField(max_length=100)),
                ('c_number', models.CharField(max_length=50)),
                ('user_nm', models.CharField(max_length=50)),
            ],
        ),
    ]
