# Generated by Django 5.0.4 on 2024-07-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_usercart'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='bought_number',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
